# Generated by Django 5.1.2 on 2024-10-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_entries_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
